function gamedetails = importgamedetails(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GAMEDETAILS1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  GAMEDETAILS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-May-2020 15:01:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["id", "pitch_length", "pitch_width", "video_fps", "ht1_frame_start", "ht1_frame_end", "kick_off_ht1", "last_event_ht1", "ht2_frame_start", "ht2_frame_end", "kick_off_ht2", "last_event_ht2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
% opts = setvaropts(opts, ["name", "date", "time"], "TrimNonNumeric", true);
% opts = setvaropts(opts, ["name", "date", "time"], "ThousandsSeparator", ",");

% Import the data
gamedetails = readtable(filename, opts);

%% Convert to output type
gamedetails = table2array(gamedetails);
end