function ballpositionsandgamecontext = importball(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BALLPOSITIONSANDGAMECONTEXT1 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the numeric
%  data.
%
%  BALLPOSITIONSANDGAMECONTEXT1 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-May-2020 15:03:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["frame", "time", "x", "y", "team_id"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ballpositionsandgamecontext = readtable(filename, opts);

%% Convert to output type
ballpositionsandgamecontext = table2array(ballpositionsandgamecontext);
end