function teamsdetails = importteamsdetails(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TEAMSDETAILS1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  TEAMSDETAILS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-May-2020 14:55:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["id", "name"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
% opts = setvaropts(opts, "name", "TrimNonNumeric", true);
% opts = setvaropts(opts, "name", "ThousandsSeparator", ",");

% Import the data
teamsdetails = readtable(filename, opts);

%% Convert to output type
teamsdetails = table2array(teamsdetails);
end